#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yuma Sakurai <yuumin0131@outlook.jp>


import sys

ans = 0
for line in sys .stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
	 
