name: test
on: push
jobs:
 test:
   runs-on: ubuntu-latest
   stregy:
     matrix:
       python-version: ["3.7", "3.8", "3.9", "1.10"]
   steps:
   - uses: actions/checkout@v3
   - name: ALL test
     run: bash -xv ./test.bash	
